### ISSUE TITLE
Need information about data in merged folder

### ISSUE THREAD

**Issue by priyacshah** [shubhampokhrel81/Fruits-and-Vegetable-Recognition-System-using-CNN#4]
Hi,

I am trying to understand your implementation. Can you please tell that what is in the merged folder? In the fruit-360_dataset of kaggle, there are 131 folders of 131 classes. Exactly what data have you used in training and testing data?

Thanks and Regards,
Priya Shah

**Comment by shubhampokhrel81** [comment]
I have only used 3 fruits and vegetables from kaggle dataset. Rest of the
dataset are created by myself. I have clicked every single degree of the
fruits and vegetables and separated them into training and testing data.

**Comment by priyacshah** [comment]
Thank you for your response, Shubham!
Can you please upload the dataset if possible?

**Comment by shubhampokhrel81** [comment]
I am sorry. I have uploaded dataset on kaggle but i couldn't find it now. i
have no backup

**Comment by priyacshah** [comment]
Okay. No problem. Thank you.
